# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20170502_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='last_active',
        ),
        migrations.AddField(
            model_name='patient',
            name='mail_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mail_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
