# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20170528_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mail_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mail_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
